spring.application.name=fileSorter

destination.file.path=D:/AnnLuciole/Sorted/
source.file.path=C:/Users/Acer/Desktop/TEST

filesorter.sort-strategy=by_year_and_month
filesorter.rename-strategy=rename_to_creation_date
